### ISSUE TITLE
DonateSpareChange needs schnorr! or at least follow preferences config.

### ISSUE THREAD

**Issue by acidsploit** [cculianu/DonateSpareChange#2]
It looks like the DonateSpareChange plugin does not respect the users wishes when it comes to the most critical user freedom upholding feature of choosing the transaction signature algorithm. 

Vitalik want Schnorr, Vitalik not impress!

Thanks! :)

![Screenshot_20190518_182432](https://user-images.githubusercontent.com/10303422/57972428-7f596400-799a-11e9-8287-8db9a2464ae5.png)

**Comment by cculianu** [comment]
Yes.  I will add it.  This plus this other plugin I maintain needs it.  Will do.

**Comment by acidsploit** [comment]
@GitCash send 0.01 BCH to @cculianu

**Comment by GitCash** [comment]
Hey **cculianu**, user **acidsploit** tipped you **10000 bits** in Bitcoin Cash ( ~ **$4.06** ).

*[Click here to claim it!](https://gitcash.io/claim/cculianu)*

You can also add the "thumbs down" reaction to **acidsploit**'s comment above to prevent future tips.

**Comment by cculianu** [comment]
Hey man thanks -- for some reason I have a BSV balance not BCH on GitCash. Whaaaa? I will report a bug.... ha ha

**Comment by acidsploit** [comment]
lolwhat? Everything is in BCH on my side..

**Comment by cculianu** [comment]
Yeah I just wrote them an email.  Hopefully they fix the bug... I don't want no stinkin' BSV!

Pretty sure it's a bug on their end.

<img width="314" alt="Screen Shot 2019-05-20 at 10 01 55 PM" src="https://user-images.githubusercontent.com/266627/58045373-f6cdf580-7b4a-11e9-9288-92d91f69d1df.png">

**Comment by cculianu** [comment]
Hey @acidsploit -- ok, this has now been implemented in latest release 1.4

https://github.com/cculianu/DonateSpareChange/releases

Schnorrrrrr
