### ISSUE TITLE
Font issue with the plus and minus button

### ISSUE THREAD

**Issue by EchterAgo** [cculianu/DonateSpareChange#4]
The plus and minus buttons use unicode symbols (Heavy plus / minus sign) that seem to not be available in every font. Sploit reported this in Telegram and I saw the same issue in the Qt Designer. This should either be switched to normal plus and minus symbols or replaced with a Vector graphic.

![image](https://user-images.githubusercontent.com/922233/59351750-4ae28900-8d49-11e9-9b53-409cf08f5b6f.png)
![image](https://user-images.githubusercontent.com/922233/59351757-4f0ea680-8d49-11e9-9414-340dabbd5676.png)

**Comment by cculianu** [comment]
Yikes! Yeah I'll fix it soon! Thanks for the issue! ! :)

**Comment by EchterAgo** [comment]
This seems to actually be caused by missing fonts. The box / box with number indicates it could not resolve a glyph for the character. For me it was solved by installing `noto-fonts-emoji` on Arch.

![image](https://user-images.githubusercontent.com/922233/59353635-a0209980-8d4d-11e9-833c-280bf755bc67.png)

**Comment by cculianu** [comment]
Is it just me or is designer notoriously careless about embedding reasonably cross platform font descriptions on the .ui file?

I’m always super scared to touch the font setting for a widget because it seems to go out of its way to break every damn time I do.

Ha ha

**Comment by EchterAgo** [comment]
Hmm, it seems that as long as you don't touch the font family you should be fine cross platform wise. To do that you need to expand the font entry. If you accidentally touched the family, just reset it. For example if I set some font to size 50 it generates this code:

```
font = QtGui.QFont()
font.setPointSize(50)
self.tb_plus.setFont(font)
```

**Comment by EchterAgo** [comment]
Like this:

![image](https://user-images.githubusercontent.com/922233/59360667-b4b75e80-8d5a-11e9-81e7-e888f442d42d.png)

There should be no reset button next to the font family. If there is, click it and it will remove that property.

**Comment by cculianu** [comment]
Yeah you are right. I "knew" this but forgot it when developing the plugin.  It's all coming back now.  "Just don't touch the font family" is the commandment.  I remember now.  Will do.
